wandb_version: 1

num_samples:
  desc: null
  value: 30
timesteps:
  desc: null
  value: 500
beta1:
  desc: null
  value: 0.0001
beta2:
  desc: null
  value: 0.02
ddim_n:
  desc: null
  value: 25
height:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692201288.01739
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.15.8
      8:
      - 1
      - 4
      - 5
