wandb_version: 1

num_samples:
  desc: null
  value: 30
timesteps:
  desc: null
  value: 500
beta1:
  desc: null
  value: 0.0001
beta2:
  desc: null
  value: 0.02
n_feat:
  desc: null
  value: 64
n_cfeat:
  desc: null
  value: 5
height:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 100
n_epoch:
  desc: null
  value: 32
lrate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692201028.067929
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.15.8
      8:
      - 1
      - 4
      - 5
